---
- name: setup pihole
  hosts: localhost
  become_method: sudo
  tasks:
    - name: "Setting hostname to 'pihole'"
      become: yes
      hostname:
        name: pihole
      tags: admin

    - name: "Disable WIFI and Bluetooth"
      become: yes
      copy: src=./files/raspi-blacklist.conf dest=/etc/modprobe.d/raspi-blacklist.conf mode=0600
      tags: admin

    - name: "Set default bash aliases"
      become: yes
      copy: src=./files/etc_profile.d_bash_aliases.sh dest=/etc/profile.d/bash_aliases.sh mode=0600
      tags: admin

    - name: "Update APT package cache"
      become: yes
      apt:
        update_cache: yes
        upgrade: safe
      tags: admin

    - name: Install admin tools (vim, htop, ntopng, nmap)
      become: yes
      apt:
        package:
          ["python-apt", "python-pip", "vim", "htop", "ntop", "nmap", "atop"]
        state: present
      tags: admin
    - name: Install PiHole Installer
      become: yes
      get_url: url=https://install.pi-hole.net dest=/tmp/pihole-installer.sh
    - name: PiHole Installer
      become: yes
      shell: /tmp/pihole-installer.sh
    - name: Remove PiHole Installer
      file:
        path: /tmp/pihole-installer.sh
        state: absent
