---
- name: setup pihole
  hosts: localhost
  become: true
  tasks:
    - name: "Setting hostname to 'pihole'"
      hostname:
        name: pihole
      tags: admin

    - name: Install curl
      become: yes
      apt:
        name: curl
        state: present
        update_cache: yes
    - name: Install PiHole Installer
      get_url: url=https://install.pi-hole.net dest=/tmp/pihole-installer.sh
    - name: PiHole Installer
      shell: /tmp/pihole-installer.sh
    - name: Remove PiHole Installer
      file:
        path: /tmp/pihole-installer.sh
        state: absent
