---
- name: setup pihole
  hosts: localhost
  become_method: sudo
  tasks:
    - name: "Setting hostname to 'pihole'"
      become: yes
      hostname:
        name: pihole
      tags: admin

    - name: "Disable WIFI and Bluetooth"
      become: yes
      copy: src=./files/raspi-blacklist.conf dest=/etc/modprobe.d/raspi-blacklist.conf mode=0600
      tags: admin

    - name: "Set default bash aliases"
      become: yes
      copy: src=./files/etc_profile.d_bash_aliases.sh dest=/etc/profile.d/bash_aliases.sh mode=0600
      tags: admin

    - name: "Update APT package cache"
      become: yes
      apt:
        update_cache: yes
        upgrade: safe
      tags: admin

    - name: Install admin tools (vim, htop, ntopng, nmap)
      become: yes
      apt:
        package:
          ["python-apt", "python-pip", "vim", "htop", "ntopng", "nmap", "atop"]
        state: present
      tags: admin
    - name: Install grin (better grep)
      shell: pip install grin
      tags: admin

    - name: Install NTP
      apt:
        package: ntp
        state: present
      tags: ntp

    - name: Copy over the NTP configuration
      template: src=files/ntp.conf dest=/etc/ntp.conf
      notify:
        - restart ntp
        - force ntp update
      tags: ntp

    - name: Make sure NTP is started up
      service: name=ntp state=started enabled=yes
      tags: ntp

    - name: "Download Pi-Hole installer"
      get_url:
        url: https://install.pi-hole.net
        dest: ~/install-pihole.sh
        mode: 0740
      tags: pihole
